//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/GamePadInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GamePadInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GamePadInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GamePadInput"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""5c9d1a06-b049-4bf3-b34f-1808d6cf944c"",
            ""actions"": [
                {
                    ""name"": ""RotateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""7a5a924c-5068-4b96-ad86-c2e561be3554"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateRight"",
                    ""type"": ""Button"",
                    ""id"": ""6d5bfd3f-b64c-4182-b15d-ea044cdaa447"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateUp"",
                    ""type"": ""Button"",
                    ""id"": ""1e3eae50-5464-414a-9f48-3a17e54e38cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateDown"",
                    ""type"": ""Button"",
                    ""id"": ""ca15a9be-e480-4ed5-bec0-b185c71ff107"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectButton"",
                    ""type"": ""Button"",
                    ""id"": ""a3f61657-cf5a-4edb-9218-ed277c767efc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldButton"",
                    ""type"": ""Button"",
                    ""id"": ""f264bc03-4aca-41f2-9ce5-5b249b688526"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e349cde7-5be6-455b-909f-9879e03c650c"",
                    ""path"": ""<AndroidGamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37d860bc-a340-4c10-bd66-eb401b1feb8a"",
                    ""path"": ""<HID::XiYuan GAME CONTOROLER>/hat/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cd9d156-3f7c-4b20-9231-2c25b8a49fce"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4edc962-a798-4902-885b-79f57519e693"",
                    ""path"": ""<AndroidGamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f321c889-010d-4f0d-a74f-e17649269092"",
                    ""path"": ""<HID::XiYuan GAME CONTOROLER>/hat/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a53ee79-c114-4086-ace2-38ee63bd111d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0ed77a8-6a04-401b-837d-9d8731ebc99b"",
                    ""path"": ""<AndroidGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0c1eda4-d154-478c-9dc3-8d6381ca8c96"",
                    ""path"": ""<HID::XiYuan GAME CONTOROLER>/hat/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dd05ee1-6d7a-407e-89a7-ebbc11999f93"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb29bab4-fa06-4412-a704-464155724e71"",
                    ""path"": ""<AndroidGamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5a65b96-bf1a-4e92-a720-0860542e5f38"",
                    ""path"": ""<HID::XiYuan GAME CONTOROLER>/hat/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""604ce4f6-ee97-4ae0-9ed7-06bc66770022"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3749d2bc-7542-4a47-a5b9-0cc94b4a2383"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22e07101-4bcf-4c46-ab3f-9f94e5bfbcdc"",
                    ""path"": ""<AndroidJoystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7bb9cbd-3b47-4e7e-b94b-6a90caf32a3d"",
                    ""path"": ""<AndroidGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3824a89-13ed-4b9c-8b0f-1a4e6030946f"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""280fb46f-f8c2-4b19-8756-d000ce5e8d80"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e49b9b7e-b359-4bdd-a8b0-c3595170e32d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd71fa48-29eb-4421-a993-0cf9bb423e90"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c02f200e-b1f3-457e-8257-5670c50b54a0"",
                    ""path"": ""<AndroidGamepad>/buttonSouth"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_RotateLeft = m_GamePlay.FindAction("RotateLeft", throwIfNotFound: true);
        m_GamePlay_RotateRight = m_GamePlay.FindAction("RotateRight", throwIfNotFound: true);
        m_GamePlay_RotateUp = m_GamePlay.FindAction("RotateUp", throwIfNotFound: true);
        m_GamePlay_RotateDown = m_GamePlay.FindAction("RotateDown", throwIfNotFound: true);
        m_GamePlay_SelectButton = m_GamePlay.FindAction("SelectButton", throwIfNotFound: true);
        m_GamePlay_HoldButton = m_GamePlay.FindAction("HoldButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private IGamePlayActions m_GamePlayActionsCallbackInterface;
    private readonly InputAction m_GamePlay_RotateLeft;
    private readonly InputAction m_GamePlay_RotateRight;
    private readonly InputAction m_GamePlay_RotateUp;
    private readonly InputAction m_GamePlay_RotateDown;
    private readonly InputAction m_GamePlay_SelectButton;
    private readonly InputAction m_GamePlay_HoldButton;
    public struct GamePlayActions
    {
        private @GamePadInput m_Wrapper;
        public GamePlayActions(@GamePadInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @RotateLeft => m_Wrapper.m_GamePlay_RotateLeft;
        public InputAction @RotateRight => m_Wrapper.m_GamePlay_RotateRight;
        public InputAction @RotateUp => m_Wrapper.m_GamePlay_RotateUp;
        public InputAction @RotateDown => m_Wrapper.m_GamePlay_RotateDown;
        public InputAction @SelectButton => m_Wrapper.m_GamePlay_SelectButton;
        public InputAction @HoldButton => m_Wrapper.m_GamePlay_HoldButton;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void SetCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterface != null)
            {
                @RotateLeft.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateLeft;
                @RotateLeft.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateLeft;
                @RotateLeft.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateLeft;
                @RotateRight.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateRight;
                @RotateRight.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateRight;
                @RotateRight.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateRight;
                @RotateUp.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateUp;
                @RotateUp.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateUp;
                @RotateUp.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateUp;
                @RotateDown.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateDown;
                @RotateDown.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateDown;
                @RotateDown.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRotateDown;
                @SelectButton.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelectButton;
                @SelectButton.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelectButton;
                @SelectButton.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelectButton;
                @HoldButton.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnHoldButton;
                @HoldButton.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnHoldButton;
                @HoldButton.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnHoldButton;
            }
            m_Wrapper.m_GamePlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RotateLeft.started += instance.OnRotateLeft;
                @RotateLeft.performed += instance.OnRotateLeft;
                @RotateLeft.canceled += instance.OnRotateLeft;
                @RotateRight.started += instance.OnRotateRight;
                @RotateRight.performed += instance.OnRotateRight;
                @RotateRight.canceled += instance.OnRotateRight;
                @RotateUp.started += instance.OnRotateUp;
                @RotateUp.performed += instance.OnRotateUp;
                @RotateUp.canceled += instance.OnRotateUp;
                @RotateDown.started += instance.OnRotateDown;
                @RotateDown.performed += instance.OnRotateDown;
                @RotateDown.canceled += instance.OnRotateDown;
                @SelectButton.started += instance.OnSelectButton;
                @SelectButton.performed += instance.OnSelectButton;
                @SelectButton.canceled += instance.OnSelectButton;
                @HoldButton.started += instance.OnHoldButton;
                @HoldButton.performed += instance.OnHoldButton;
                @HoldButton.canceled += instance.OnHoldButton;
            }
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);
    public interface IGamePlayActions
    {
        void OnRotateLeft(InputAction.CallbackContext context);
        void OnRotateRight(InputAction.CallbackContext context);
        void OnRotateUp(InputAction.CallbackContext context);
        void OnRotateDown(InputAction.CallbackContext context);
        void OnSelectButton(InputAction.CallbackContext context);
        void OnHoldButton(InputAction.CallbackContext context);
    }
}
